dist: focal
language: python
python:
- '3.8'
install:
- pip install -r requirements-dev.txt
before_script:
- python -m pylint merakitoolkit/
script:
- python -m pytest tests/ -v -s
deploy:
  provider: pypi
  username: __token__
  password:
    secure: rJ092AnSdZEY+MQ/CEQlTXjvZFgt7jVB1rvGq7RLsFi9NC69wrO+PF/dC8yOoDvEaRgKTqkrr+dHjZogrlpgzvRypAft512Hny0ZWqOCXs+JO9pIpr3lescGuOOQqnNHkgA76K6GJlVriJ0b7C7xWsvNzQikOOTDHdG3I7L0gkhpfMGk4faJAzGW4hxY0t9pQ9hsedO3+F+UicX73xE6Tt2+ldj0lsJ/VeBu1VUqb7IdUrP+Nie4v9L4hXZZfVjQvD1GRkmeCN0YP1/d7rsscoSh2yYnnKKlZG+EvWDxRXkUeWYvg42qpEcw3f5bBL4wP/ju+G2Rc0EH6fOeCkfB3pvGVVTBOzt+HR03y5g1ggkCCV0cqiLMqMtwPShou2df+qEfnzdNDCOG3bOBoD2Z2b2uxoXjMHTlyq3zMDAo6fRkzxspoio4YEXZcnVMlu49ouucqVgxx3waG3Y50CCwa+vcOMh5HPEmNdn0JaVKz+OXOmIRDLdkVVPEXRnBicQc8etguHX2FoxW89yaN4gwjGMDToel5cpgr08yEEtJ36FbJc9BX0VtWStZZRMxMI/zEs3Hq1fhl/dUQ5F1O57gnQV8rxk9JIt50wz1JwqhyQihiqW1L1rTezfpzNsFSjGvlZ6B1rjh5OgImVL+ZtSlyI/kv8b7XUZN+Hxe7WTqrQM=
  on:
    branch: main
  distributions: "sdist bdist_wheel"
  skip_existing: true
